//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensayo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class prueba
    {
        public int idPrueba { get; set; }
        public string cmpTexto { get; set; }
        public Nullable<decimal> cmpNumero { get; set; }
        public Nullable<System.DateTime> cmpFecha { get; set; }
    }
}
